# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVLr7AM1dwoGIk4TUWnhkT7ggFcoTrN0

**[Milestone 1](https://)**

**Project Name : Agriculture Crop Yield**

**The dataset**
"""

df = pd.read_csv('crop_yield.csv')
df

"""**At least 10 columns with varying data types**

**At least 100 rows (data points).**
"""

display(df.head(100))

df.info()

df.sample(10)

# statistical value

df.describe()