# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVLr7AM1dwoGIk4TUWnhkT7ggFcoTrN0

**[Milestone 1](https://)**

**Project Name : Agriculture Crop Yield**

**The dataset**
"""

df = pd.read_csv('crop_yield.csv')
df

"""**At least 10 columns with varying data types**

**At least 100 rows (data points).**
"""

display(df.head(100))

df.info()

df.sample(10)

# statistical value

df.describe()

df.sample(10)

"""**[Milestone 2](https://)**

**Sampling Assignment**

**Implementing Probability Sampling Methods in Python**

Instructions

Upload your dataset (minimum 200 rows), then complete all parts A–F.

**Part A — Setup**
**Report dataset size (rows, columns)**
"""

import pandas as pd
import numpy as np


df = pd.read_csv('/content/crop_yield.csv')
df.head(10)

print("Dataset size:", df.shape)
population_mean = df['Temperature_Celsius'].mean()

"""**Part B — Simple Random Sampling (20 points)**"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/crop_yield.csv')
df.head(50)

sample_df = df.sample(n=50, random_state=42)
sample_mean = sample_df['Temperature_Celsius'].mean()


print(f"Population Mean (Temperature_Celsius): {population_mean:.2f}")
print(f"Sample Mean (Temperature_Celsius, n=50): {sample_mean:.2f}")

"""
**Part B — Simple Random Sampling**
"""

sample_size = 50
srs = df.sample(n=sample_size, random_state=42)
display(srs.head())
population_mean = df['Temperature_Celsius'].mean()
print("Population mean:", population_mean)
srs_mean = srs['Temperature_Celsius'].mean()
print("Sample mean:", srs_mean)

"""**Part C — Systematic Sampling**"""

n = 50
k = len(df) // n
start = np.random.randint(0, k)
sys_sample = df.iloc[start::k][:n]
display(sys_sample.head())
sys_mean = sys_sample['Temperature_Celsius'].mean()
print ("\n")
print("Sample mean:", sys_mean)

"""**Part D — Stratified Sampling**"""

strata_col = "Region"  # Corrected to an existing column
sample_size = 50

# proportional fraction for each group
frac = sample_size / len(df)

# stratified sample
stratified_sample = df.groupby(strata_col, group_keys=False).sample(frac=frac, random_state=42)

display(stratified_sample.head())
strat_mean = stratified_sample['Temperature_Celsius'].mean() # Corrected column name

print ("\n")
print("Sample mean:", strat_mean)

"""**Part E — Cluster Sampling**"""

df['cluster_id'] = df.index // (len(df)//10)  # 10 clusters
selected_clusters = np.random.choice(df['cluster_id'].unique(), size=2, replace=False)
cluster_sample = df[df['cluster_id'].isin(selected_clusters)]
print("Selected clusters:", selected_clusters)
display(cluster_sample.head())
cluster_mean = cluster_sample['Temperature_Celsius'].mean() # Corrected column name

print ("\n")
print("Sample mean:", cluster_mean)

"""
**Part F — Comparison & Reflection**


Compare sample means vs population mean, then write your reflection."""

df['cluster_id'] = df.index // (len(df)//10)  # 10 clusters
selected_clusters = np.random.choice(df['cluster_id'].unique(), size=2, replace=False)
cluster_sample = df[df['cluster_id'].isin(selected_clusters)]
print("Selected clusters:", selected_clusters)
cluster_sample.head()

comparison = pd.DataFrame({
    'Method': ['Simple Random', 'Systematic', 'Stratified', 'Cluster'],
    'Sample Mean': [srs_mean, sys_mean, strat_mean, cluster_mean],
    'Population Mean': [population_mean]*4,
    'Difference': [(srs_mean - population_mean),
                   (sys_mean - population_mean),
                   (strat_mean - population_mean),
                   (cluster_mean - population_mean)]
})
print(comparison)

"""**Part F — Comparison & Reflection**"""

print ("Compare sample means vs population mean, then write your reflection.")

print ("In this milestone, I applied four probability sampling methods to the\nAgricultureCrop Yield dataset from Kaggle, which includes crop production\ndata across multiple countries.\nThe goal was to compare Simple Random Sampling, Systematic Sampling,\nStratified Sampling and Cluster Sampling in estimating the population mean of\ncrop yield, which was 32.337344 t/ha.\nStratified sampling produced the most accurate result with a mean of 32.3276\nt/ha, as proportional allocation preserved the distribution of crop types and\nregions.\nSimple Random Sampling yielded 32.25 t/ha, slightly lower, while systematic\nsampling gave 32.3872 t/ha, slightly higher.\nCluster sampling showed the largest deviation at 32.5075 t/ha due to\npotential homogeneity within clusters.\nIn terms of implementation, Simple Random Sampling was easiest, requiring\nminimal code.\nSystematic sampling was straightforward with a defined step size, while\nstratified sampling needed careful grouping.\nCluster sampling was simple but required thoughtful cluster selection.")

print("Overall, stratified sampling ensured maximum accuracy, and Simple Random\nSam- pling was the simplest to implement.")